### ISSUE TITLE
The component rich-text doesn't exist in your Storyblok Space

### ISSUE THREAD

**Issue by apatwary12** [storyblok/wordpress-importer#3]
I'm trying to use the default script on my wordpress build and i'm getting a rich-text doesn't exist. Which is supposed to be a default right? I also set up the schema to the exact set up that is in the https://www.storyblok.com/mp/workshop-recap-migrate-wordpress-headless workshop slides.

**Comment by christianzoppi** [comment]
Thanks. Are you sure the space id is correct and that the `rich-text` component exists in the space?
