### ISSUE TITLE
config.folder does not seem to be used

### ISSUE THREAD

**Issue by uuf6429** [storyblok/wordpress-importer#7]
The readme mentions a top-level `folder` (in `config`) but it doesn't seem to work nor does it seem to be used in the code.
There is however a `content_type.folder` field, so maybe this is just a mistake in the documentation?

**Comment by uuf6429** [comment]
@christianzoppi perhaps I should have been clearer on what I meant:

<img width="759" alt="image" src="https://user-images.githubusercontent.com/230049/179976798-7c0c6286-d1dc-42ba-9803-1eea8cc73150.png">

**Comment by uuf6429** [comment]
Hey, I'm looking further at the documentation and there seems to be more inaccuracies and ambiguities.

For example, this doesn't seem to do anything (and is in any case not documented):
https://github.com/storyblok/wordpress-importer/blob/main/README.md?plain=1#L71

Or here:
https://github.com/storyblok/wordpress-importer/#wordpress-blocks-mapping
the documentation says **blocks_mapping** but the sample code uses **schema_mapping**.. which one is right?

**Comment by christianzoppi** [comment]
@uuf6429 I get what you mean, I'll place the `folder` attribute in the right position. In regards to the mapping attributes, those are two different things and they are explained in the readme.
